### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by C0ZEN** [primefaces/primereact-examples#20]
I wanted to test `nextjs-styled`.
Simply did `npm i` and `npm run dev` and got an error.

```
SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.mod.require (/Users/x/Documents/github/primereact-examples/nextjs-styled-tailwind/node_modules/next/dist/server/require-hook.js:64:28)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/x/Documents/github/primereact-examples/nextjs-styled-tailwind/node_modules/next/dist/telemetry/post-payload.js:17:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:40089) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:40089) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Process finished with exit code 0
```

Any idea?

**Comment by C0ZEN** [comment]
Got the wrong version of `node`.
Migrated to `18` and it's fine.
